Add options WITH_SSL and WITH_ZLIB
bincrafters/conan-mysql-connector-c pull request #6
Opened 2018-07-03 02:22 UTC by msteinert

Mysql-connector-c includes an embedded SSL library (yassl) and an embedded
Zlib. WITH_SSL and WITH_ZLIB can be set to "system" to link with system
versions of OpenSSL and Zlib. This patch allows these options to be set
and then adds dependencies on the Conan.io OpenSSL and Zlib packages.

2018-07-03 03:56 UTC, uilianries requested changes
We use `with_xxx` as boolean option

2018-07-03 03:57 UTC, uilianries commented
Hi @msteinert !

Thanks for your contribution!

2018-07-04 03:52 UTC, SSE4 approved these changes
LGTM

2018-07-04 12:18 UTC, uilianries approved these changes

2018-07-04 12:18 UTC, merged